### PR TITLE
Create Databases-101

### PR DESCRIPTION
**Pull request by abigailcstone**
technology cat

### CODE REVIEW

**Comment by lawsonanderson** [comment]
Thanks for sharing all of this info on databases @abigailcstone !  I did not recall that graph databases are used in logistics and the transportation industry so thanks for bringing that to my attention!  Rock on! :+1:

**Comment by CKnaupp15** [comment]
@abigailcstone Thanks for wrapping up our learnings on databases. That's a great reminder! Is there any chance you could provide a picture summarizing/visualizing the differences, and add a link for further information? Good stuff! :+1:

**Comment by MQin15** [comment]
@abigailcstone Great summary! If you want to add a picture in your writing and mention us in the post, use the coding below:
+Alt Text 
+Please provide feedback: @jenadeng, @oscar14, @abigailcstone, @mqin15, @cknaupp15

**Comment by MQin15** [comment]
oops, the previous one did work. for picture, it is <Alt Text> (link)

**Comment by jenadeng** [comment]
@abigailcstone love the picture! :smile_cat: I thought your summary on databases was very thorough and helpful for people who did not know anything about databases (like myself!). I'm curious to see how the NuSQL databases will evolve from here. 
:+1:

**Pull request merged**
