### PR TITLE
Managing people

### PR DESCRIPTION
**Pull request by oscar14**
Hi guys.  I'd love your insights on my blurb-- @CKnaupp15 @abigailcstone @lawsonanderson @MQin15 @jenadeng .  Thanks in advance

### CODE REVIEW

**Comment by MQin15** [comment]
Managing people is easier than managing github

**Comment by jenadeng** [comment]
Amen @MQin15 !

**Comment by CKnaupp15** [comment]
@MQin15 Agree!

**Comment by CKnaupp15** [comment]
Hi @oscar14, great article! Adding to what you wrote, I also learned that it always takes a balance between breadth (having a broad interest in what is going on) vs depth (it is hard to be an expert in all programming languages, and better to know one or two really well). I can't see your picture yet, any way I can help you put it in?

**Comment by jenadeng** [comment]
@oscar14 very insightful summary of your learnings. Programmers are people too! Another thing I took away was the importance of finding people who are passionate about their work because passion can't be taught or faked. :open_hands:

:+1:

**Comment by lawsonanderson** [comment]
@oscar14 Awesome takeaways!  One word that I kept hearing in class was "empathy".  I think this is a critical value/virtue for managing people and one that you communicate well in your write-up!

**Comment by lawsonanderson** [comment]
@oscar14 :+1:

**Comment by CKnaupp15** [comment]
@oscar14 :+1: for the picture! Managing people is fun! (and MBAs favourite thing to do anyways) ;)

**Comment by abigailcstone** [comment]
Very good point about the metaphor--I was also surprised. Also true about github...and that programmers are people too! :+1:

**Pull request merged**
