### PR TITLE
Running lean and mean

### PR DESCRIPTION
**Pull request by lawsonanderson**
Please provide any feedback you have on the Lean Startup branch at your convenience!

@jenadeng @abigailcstone @MQin15 @oscar14 @CKnaupp15

### CODE REVIEW

**Comment by lawsonanderson** [comment]
@jenadeng This is a very insightful summary, thanks very much for sharing!  I really like the photo too!

**Comment by MQin15** [comment]
Lean concept works in lots of places but not in the governments....

**Comment by jenadeng** [comment]
@lawsonanderson Cowabunga! Awesome post. I personally don't understand what "convex dollars" means but I'm not very English literate. However, great summary of the takeaways from the specifying software segment and insights into how to efficiently develop a product.

**Comment by jenadeng** [comment]
:+1:

**Comment by CKnaupp15** [comment]
@lawsonanderson Spot on! Super-important for start-ups to have a MVP to test user acceptance and improve upon. Does that really make them mean already - is that what the picture is hinting at? I didn't quite get that (lost in translation for me) but it looks fun :+1:

**Comment by oscar14** [comment]
Hi.  Enjoyed this summary.  At first, the Concierge MVP concept seemed like putting cart before horse.  What if you cannot code a solution that delivers the humunculus solution?!  But now we know that coding can do almost anything, and it's more important to find a monetizable offering first rather than sink money into developing a bunch of non-monetizable code. :+1:

**Pull request merged**
