### PR TITLE
Website vs app

### PR DESCRIPTION
**Pull request by CKnaupp15**

### CODE REVIEW

**Comment by CKnaupp15** [comment]
Hi team! @MQin15 @oscar14 @lawsonanderson @abigailcstone @jenadeng
I just uploaded my lessons learned on websites vs. apps and would really appreciate your feedback!
lmk, thanks!
Cherilyn

**Comment by MQin15** [comment]
@CKnaupp15 Looking great!! Apps are taking over the world.

**Comment by lawsonanderson** [comment]
@CKnaupp15 This is a great reference for entrepreneurs and will be very helpful as I think about managing costs going forward.  High five!  :+1:

**Comment by jenadeng** [comment]
@CKnaupp15 very clear and concise summary of the advantages between a :computer: versus :iphone: ! The graphic was super helpful in highlighting the difference between the two. A note about which type of business should start with what might be helpful as a follow-up post.

:+1:

**Comment by oscar14** [comment]
Hi Cherilyn.  This topic is an important one, given the number of people that are starting and scaling their tech-enabled start-ups.  If you ask these techpreneurs, the most compelling reason for "going app" is functionality.  They want a slick user experience.  It will be interesting to see what the pile of old vintage 2015 apps looks like a few years from now.  I doubt they'll age as well as a good wine. ;) Thanks for the review of this important topic.  :+1:

**Comment by abigailcstone** [comment]
Thanks so much for this! I also found it quite helpful. I'm actually at the URX office at the moment and they are all about facilitating interactions between apps and from web browsers to apps through their mobile app index and deeplinks. With more native apps, I'm excited to see new technologies emerge to allow them to "break out of their sandboxes." :+1:

**Pull request merged**
