### PR TITLE
Mian liking it

### PR DESCRIPTION
**Pull request by MQin15**

### CODE REVIEW

**Comment by jenadeng** [comment]
@MQin15 love the graphic. Very representative of the concepts we learned in class, but it looks like a very complicated process. Good thing the text explains the four phases of "to do", "design", "development", and "done". :+1: :+1:  from me!

**Comment by lawsonanderson** [comment]
@MQin15 Wow, what a fancy picture!  Where can I read even more on this topic?  Super cool!

**Comment by MQin15** [comment]
@jenadeng Thank you! Not as complicated as the github logic :palm_tree:

**Comment by lawsonanderson** [comment]
Oh, and I almost forgot :+1:

**Comment by oscar14** [comment]
Hi Mian.  This is a good overview.  If you were the manager overseeing this Kanban board, what would be your next most important thing for the team to do (given the current layout of post-its on the board)?  Thanks

**Comment by MQin15** [comment]
@oscar14 Great Question!! Too many things in Backlog and not enough work for people we are managing the Merge session, so move developers to work on Backlog! No tea breaks for today!

**Comment by CKnaupp15** [comment]
@MQin15 I love Kanban, too! Thank you for the post and for summarizing our class learnings on this topic. This is a great summary. Is there any chance you could format the text in paragraphs / or even bullet points to enhance quick legibility? And do you have a link for further information? Thank you! :+1:

**Comment by MQin15** [comment]
@CKnaupp15 Thank you for the thoughtful comment. I noticed that the format is a kinda off. I just reformatted the paragraphs. Here is a link. http://en.wikipedia.org/wiki/Kanban 
I also just realized that this operational method is from Japan and the Japanese name means "showing board," and the same thing in Chinese.

**Comment by abigailcstone** [comment]
@MQin15 This is excellent! I, too, love the kanban board concept. We learned about this at a timely moment for me as a first year as we just covered the Toyota Production System in Operations Management, which the concept of kanban is included in. Thank you! :+1:

**Pull request merged**
